OPENROUTER_API_KEY = "your_openrouter_api_key_here"
GOOGLE_API_KEY = "your_google_api_key_here"
GOOGLE_CSE_ID = "your_google_cse_id_here"
WOLFRAM_APP_ID = "your_wolfram_app_id_here"
OPENWEATHER_API_KEY = "your_openweather_api_key_here"
NEWS_API_KEY = "your_news_api_key_here"
