OPENROUTER_API_KEY = "your_openrouter_key"
GOOGLE_API_KEY = "your_google_api_key"
GOOGLE_CSE_ID = "your_google_cse_id"
WOLFRAM_APP_ID = "your_wolfram_app_id"
OPENWEATHER_API_KEY = "your_openweather_api_key"
NEWS_API_KEY = "your_news_api_key"
